Update dependencies for Django 5.x compatibility
Louxsdon/django-breeze pull request #8
Opened 2024-09-24 20:31 UTC by diegoquiroz

Update inertia-django and django-vite to Django 5 compatible versions.

2024-09-25 00:50 UTC, Louxsdon reviewed
Thanks for the PR

2024-09-25 00:51 UTC, Louxsdon requested changes
Updating the dependencies alone could break the project without the API change implementations.

Kindly cross-check the API changes for the respective dependencies to ensure that code bases comply with them.

2024-09-25 02:05 UTC, diegoquiroz commented
Done! I checked both [inertia-django](https://github.com/inertiajs/inertia-django/commits/main/) which contained changes only to readme and compatibility for Django 5, and [django-vite](https://github.com/MrBin99/django-vite) which had only fixes but none of them impact the usage of Django-Breeze.

2024-09-27 14:54 UTC, Louxsdon approved these changes

2024-09-27 14:56 UTC, merged